import Head from 'next/head';

export default function Home(): JSX.Element {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
        </Head>
    )
}
